### ISSUE TITLE
Blueprint incorrect 

### ISSUE THREAD

**Issue by Ingeloaka** [dododex/dododex.github.io#1]
The X-mosasaurus blueprint is "Blueprint'/Game/Genesis/Dinos/BiomeVariants/Ocean_Mosa/Ocean_Mosa_Character_BP.Ocean_Mosa_Character_BP'" should read "...BiomeVariants/Ocean_Mosasaurus/" to correct it, does nothing currently.

**Comment by danleveille** [comment]
Fixed previously. :)
