### ISSUE TITLE
When I enter any creature info and try to slide the knock out it 

### ISSUE THREAD

**Issue by omarally** [dododex/dododex.github.io#13]

**Comment by danleveille** [comment]
@omarally Can you explain what you mean? And are you referring to the admin commands feature? This is an issue tracker for the admin commands.

**Comment by omarally** [comment]
> @omarally Can you explain what you mean? And are you referring to the admin commands feature? This is an issue tracker for the admin commands.

Every time I slide the knock out slider it goes back

**Comment by omarally** [comment]
> > @omarally Can you explain what you mean? And are you referring to the admin commands feature? This is an issue tracker for the admin commands.
> 
> Every time I slide the knock out slider it goes back

Never mind I figured it out
